### PR TITLE
Adding test for getElementXPath

### PR DESCRIPTION
**Pull request by vdebroy**
Adding test under the xpath group for the function: getElementXPath. Current set of tests only check the getElementTreeXPath function and don't take into account elements with ids.

### CODE REVIEW

**Comment by vdebroy** [comment]
Eventually maybe the getElementTreeXPath function can be modified to return the full path if none of the elements in the chain have an id, and alternatively if one of the elements in the chain has an id, return the path from that element to the element being examined.

**Comment by janodvarko** [comment]
Hi, thanks for the patch!
Would you be interested in contributing to Firebug.next?
https://github.com/firebug/firebug.next

We are (the Firebug team) focusing on Firebug 3 and Firebug 2 is only under maintenance mode...

Honza

**Comment by vdebroy** [comment]
Absolutely! I will start looking into firebug.next right away :)

Should I close this pull request then?

Thank you.

- Vidroha

**Comment by janodvarko** [comment]
Great

Yes please, you can close this one.

Some instructions how to start hacking on Firebug.next (aka Firebug 3)
https://github.com/firebug/firebug.next/#hacking-on-firebugnext-aka-firebug-3

Thanks
Honza

**Pull request closed without merging**
