### PR TITLE
Issue #7917: Introduce extensions.firebug.listenDynamicScripts option

### PR DESCRIPTION
**Pull request by fflorent**
@janodvarko Could you review this PR please?

### CODE REVIEW

**Comment by janodvarko** [comment]
Looks good to me!

The only thing is the name of the pref.  Could we rather call is something like "ignoreDynamicScripts"?

It's ok for me if the "allowSource" change is part of this patch.

Honza

**Comment by fflorent** [comment]
Updated. I'll do the merge this evening

Florent

**Comment by janodvarko** [comment]
Excellent

Honza

**Comment by fflorent** [comment]
Done https://github.com/firebug/firebug/commit/72de59443ba383e4b39c25b141dae1c797f9faa2

Florent

**Comment by SebastianZ** [comment]
I believe this preference should default to `true`.

Also, an IMO better approach would have been to only show dynamic scripts when they have a `//# sourceURL` as described at https://github.com/firebug/firebug/issues/7827#issuecomment-103610925. Though I guess it's not worth the effort.

Sebastian

**Pull request closed without merging**
